name: LibNDS
on:
  push:
    branches:
    - main
jobs:
  build-wii:
    runs-on: ubuntu-latest
    container: devkitpro/devkitarm:latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Compile
      run: |
        make -f Makefile(5)
    - name: Upload
      uses: actions/upload-artifact@v4
      with:
        name: nds
        path: |
          .
